# Generated by Django 5.2.16 on 2026-07-20 23:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='identificador')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('SUSPENDED', 'Suspenso'), ('CLOSED', 'Encerrado')], default='ACTIVE', max_length=16)),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ('name',),
            },
        ),
    ]
