#!/bin/sh
set -eu
psql --set=ON_ERROR_STOP=1 --set=app_password="$CIPA_APP_PASSWORD" \
  --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
SELECT format(
  'CREATE ROLE cipa_app LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS',
  :'app_password'
)
WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'cipa_app') \gexec
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO cipa_app;
GRANT USAGE ON SCHEMA public TO cipa_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cipa_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO cipa_app;
EOSQL
