# Generated by Django 5.2.16 on 2026-07-20 23:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('registration_id', models.CharField(blank=True, max_length=32, verbose_name='CNPJ ou identificação')),
                ('cnae', models.CharField(blank=True, max_length=16, verbose_name='CNAE')),
                ('risk_degree', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='grau de risco')),
                ('employee_count', models.PositiveIntegerField(default=0, verbose_name='quantidade de empregados')),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('postal_code', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('predominant_union', models.CharField(blank=True, max_length=180, verbose_name='sindicato predominante')),
                ('responsible_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do responsável')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo')], default='ACTIVE', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='organizations.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ('company__corporate_name', 'name'),
                'indexes': [models.Index(fields=['tenant', 'status'], name='est_tenant_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='establishment_company_name_unique'), models.UniqueConstraint(condition=models.Q(('registration_id', ''), _negated=True), fields=('tenant', 'registration_id'), name='establishment_tenant_reg_unique')],
            },
        ),
    ]
