# Generated by Django 5.2.16 on 2026-07-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='postal_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
    ]
