# Generated by Django 5.2.16 on 2026-07-20 23:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0001_initial'),
        ('organizations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_key', models.CharField(max_length=64, unique=True)),
                ('current_hash', models.CharField(blank=True, max_length=64)),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_chain_head', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=64)),
                ('sequence', models.PositiveBigIntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('justification', models.TextField(blank=True, max_length=2000)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('current_hash', models.CharField(max_length=64, unique=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.company')),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='establishments.establishment')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-occurred_at', '-sequence'),
                'indexes': [models.Index(fields=['tenant', 'event_type', 'occurred_at'], name='audit_event_lookup_idx'), models.Index(fields=['actor', 'occurred_at'], name='audit_actor_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'sequence'), name='audit_tenant_sequence_unique')],
            },
        ),
    ]
