# Generated by Django 5.2.16 on 2026-07-20 23:43

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('kind', models.CharField(choices=[('DIRECT_COMPANY', 'Empresa direta'), ('CONSULTANCY', 'Consultoria')], max_length=20, verbose_name='tipo')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa')], default='ACTIVE', max_length=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate_name', models.CharField(max_length=200, verbose_name='razão social')),
                ('trade_name', models.CharField(blank=True, max_length=180, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=14, validators=[apps.core.validators.validate_cnpj], verbose_name='CNPJ')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa'), ('SUSPENDED', 'Suspensa')], default='ACTIVE', max_length=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='organizations.organization')),
            ],
            options={
                'ordering': ('corporate_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='organization_tenant_name_unique'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['tenant', 'status'], name='company_tenant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('tenant', 'cnpj'), name='company_tenant_cnpj_unique'),
        ),
    ]
